name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: m2-${{ runner.os }}-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          m2-${{ runner.os }}-${{ matrix.java-version }}
          m2-${{ runner.os }}
          m2
    - run: mvn clean install
